export enum ErrorCodes {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  NOT_FOUND = 'NOT_FOUND',
  CONFLICT = 'CONFLICT',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  BUSINESS_RULE_VIOLATION = 'BUSINESS_RULE_VIOLATION',
  INFRASTRUCTURE_ERROR = 'INFRASTRUCTURE_ERROR',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
